baseURL = "https://david-beauchesne.github.io/"
languageCode = "en-us"
title = "David Beauchesne's Website"
theme = "anatole"
DefaultContentLanguage = "en"

[params]
title = "David Beauchesne"
author = "David Beauchesne"
description = "Postdoctoral researcher"
profilePicture = "images/DavidBeauchesne.jpg"
rss = true

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:david.beauchesne@hotmail.com"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/david-beauchesne"

[[params.socialIcons]]
icon = "fab fa-researchgate"
title = "ResearchGate"
url = "https://www.researchgate.net/profile/David_Beauchesne"

[[params.socialIcons]]
icon = "fab fa-orcid"
title = "ORCID"
url = "https://www.orcid.org/0000-0002-3590-8161"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/d_beauchesne"


[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/david-beauchesne-16683353/"

[[params.socialIcons]]
icon = "fas fa-rss"
title = "RSS"
url = "https://david-beauchesne.github.io/index.xml"


# [[params.socialIcons]]
# icon = "ai ai-google-scholar-square"
# title = "Google Scholar"
# url = "https://david-beauchesne.github.io/index.xml"

# Google scholar: https://scholar.google.ca/citations?user=8YPeWfgAAAAJ&hl=en&oi=ao
# Impact story: https://impactstory.org/u/0000-0002-3590-8161

[Languages]
  [Languages.en]
  title = "David Beauchesne"
  description = """
  Postdoctoral researcher
  Co-founder inSileco Inc.
  """
  weight = 1
  LanguageName = "EN"

  [Languages.fr]
  title = "David Beauchesne"
  description = """
  Chercheur postdoctoral
  Co-fondateur inSileco Inc.
  """
  weight = 2
  LanguageName = "FR"


# =~-~=~-~=~-~=~-~=~-~=~-~=~-~=~-~=~-~=~-~=~-~=~-~=~-~=~-~=~-~=~-~=~-~=~-~=~-~ #
[menu]

  # -----------------------------------------------
  # English menu
  [[Languages.en.menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[Languages.en.menu.main]]
  name = "Vitae"
  identifier = "vitae"
  weight = 100
  url = "/cv/"

  [[Languages.en.menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[Languages.en.menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"


  # -----------------------------------------------
  # Menu français
  [[Languages.fr.menu.main]]
  name   = "Menu"
  identifier = "home"
  weight = 100
  url    = "/fr/"

  [[Languages.fr.menu.main]]
  name = "Billets"
  weight = 200
  identifier = "posts"
  url = "/fr/post/"

  [[Languages.fr.menu.main]]
  name = "À propos"
  weight = 300
  identifier = "about"
  url = "/fr/apropos/"
